<a href="https://colab.research.google.com/github/Amrutha9010/AMU_Webpage/blob/main/ml_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('expanded_sleep_health_dataset.csv', keep_default_na=False)
print(df.head())

   Person ID  Gender  Age         Occupation  Sleep Duration  \
0          1    Male   41              Nurse             7.0   
1          2    Male   42  Software Engineer             6.7   
2          3  Female   45             Doctor             8.7   
3          4    Male   24             Writer             8.0   
4          5  Female   18        Salesperson             8.8   

   Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                 5                       91            10       Normal   
1                 7                      123             5   Overweight   
2                 4                       49             7       Normal   
3                 6                        4             5       Normal   
4                 6                       66             4   Overweight   

          Blood Pressure  Heart Rate  Daily Steps Sleep Disorder  
0              111/71.15          56         9476           None  
1  129/85.85000000000001      

In [ ]:
df.isnull().sum()

Person ID                  0
Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Blood Pressure             0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Person ID                1500 non-null   int64  
 1   Gender                   1500 non-null   object 
 2   Age                      1500 non-null   int64  
 3   Occupation               1500 non-null   object 
 4   Sleep Duration           1500 non-null   float64
 5   Quality of Sleep         1500 non-null   int64  
 6   Physical Activity Level  1500 non-null   int64  
 7   Stress Level             1500 non-null   int64  
 8   BMI Category             1500 non-null   object 
 9   Blood Pressure           1500 non-null   object 
 10  Heart Rate               1500 non-null   int64  
 11  Daily Steps              1500 non-null   int64  
 12  Sleep Disorder           1500 non-null   object 
dtypes: float64(1), int64(7), object(5)
memory usage: 152.5+ KB


In [ ]:
df.describe()

Person ID          Age  Sleep Duration  Quality of Sleep  \
count  1500.000000  1500.000000     1500.000000       1500.000000   
mean    750.500000    48.394667        7.751733          5.825333   
std     433.157015    18.160510        0.900761          1.782772   
min       1.000000    18.000000        5.100000          1.000000   
25%     375.750000    33.000000        7.200000          5.000000   
50%     750.500000    47.000000        7.700000          6.000000   
75%    1125.250000    64.000000        8.400000          7.000000   
max    1500.000000    80.000000       10.000000         10.000000   

       Physical Activity Level  Stress Level   Heart Rate  Daily Steps  
count              1500.000000   1500.000000  1500.000000   1500.00000  
mean                 59.190000      6.012000    74.763333   6119.56600  
std                  38.266636      2.366909    12.237340   2823.00209  
min                   0.000000      1.000000    43.000000   1000.00000  
25%                  30.000000      4.000000    66.000000   3983.50000  
50%                  55.000000      6.000000    75.000000   5823.50000  
75%                  83.250000      8.000000    83.000000   8028.00000  
max                 180.000000     10.000000   109.000000  16036.00000

In [ ]:
for col in df.columns:
    print(f"{col} → {df[col].unique()}")

Person ID → [   1    2    3 ... 1498 1499 1500]
Gender → ['Male' 'Female']
Age → [41 42 45 24 18 78 21 50 68 71 46 77 23 30 69 56 51 75 61 37 31 72 19 60
 20 39 35 64 58 33 73 79 36 67 43 49 38 40 65 44 57 63 53 54 26 29 62 66
 52 34 55 59 25 70 80 74 47 28 48 76 27 32 22]
Occupation → ['Nurse' 'Software Engineer' 'Doctor' 'Writer' 'Salesperson' 'Manager'
 'Lawyer' 'Artist' 'Accountant' 'Sales Representative' 'Engineer'
 'Scientist' 'Chef' 'Student' 'Teacher']
Sleep Duration → [ 7.   6.7  8.7  8.   8.8  7.7  6.8  7.2  7.5  8.5  7.3  8.2  7.8  7.4
  7.6  9.5  7.1  5.8  8.6 10.   6.4  8.3  9.   8.4  9.3  9.4  6.3  6.6
  6.5  9.1  8.1  6.9  5.5  7.9  9.2  5.7  9.9  6.   6.2  9.7  8.9  6.1
  5.6  9.6  5.2  5.4  5.3  9.8  5.9  5.1]
Quality of Sleep → [ 5  7  4  6  3  9  1  8  2 10]
Physical Activity Level → [ 91 123  49   4  66  34  35  30  37  26  23  93   7  59  65  68 142 127
  51 106  50  21  52  99   0 128  13  63 157  45  31  20  36  43 118  86
 100  22  16  14  79  53  58  42   2  67

In [ ]:
df.drop('Person ID', axis=1, inplace=True)

In [ ]:
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})

In [ ]:
df = pd.get_dummies(df, columns=['Occupation'], drop_first=True)

In [ ]:
print(df.head())

   Gender  Age  Sleep Duration  Quality of Sleep  Physical Activity Level  \
0       0   41             7.0                 5                       91   
1       0   42             6.7                 7                      123   
2       1   45             8.7                 4                       49   
3       0   24             8.0                 6                        4   
4       1   18             8.8                 6                       66   

   Stress Level BMI Category         Blood Pressure  Heart Rate  Daily Steps  \
0            10       Normal              111/71.15          56         9476   
1             5   Overweight  129/85.85000000000001          67        10661   
2             7       Normal  119/79.35000000000001          60         5033   
3             5       Normal                98/62.7          97         1610   
4             4   Overweight               110/66.5          71         6574   

   ... Occupation_Lawyer  Occupation_Manager  Occupation

In [ ]:
bmi_order = {'Underweight': 0, 'Normal': 1, 'Overweight': 2, 'Obese': 3}
df['BMI Category'] = df['BMI Category'].map(bmi_order)

In [ ]:
print(df.head())

   Gender  Age  Sleep Duration  Quality of Sleep  Physical Activity Level  \
0       0   41             7.0                 5                       91   
1       0   42             6.7                 7                      123   
2       1   45             8.7                 4                       49   
3       0   24             8.0                 6                        4   
4       1   18             8.8                 6                       66   

   Stress Level  BMI Category         Blood Pressure  Heart Rate  Daily Steps  \
0            10             1              111/71.15          56         9476   
1             5             2  129/85.85000000000001          67        10661   
2             7             1  119/79.35000000000001          60         5033   
3             5             1                98/62.7          97         1610   
4             4             2               110/66.5          71         6574   

   ... Occupation_Lawyer  Occupation_Manager  Occu

In [ ]:
bp_split = df['Blood Pressure'].str.split('/', expand=True)
df['Systolic_BP'] = pd.to_numeric(bp_split[0])
df['Diastolic_BP'] = pd.to_numeric(bp_split[1])
df.drop('Blood Pressure', axis=1, inplace=True)
print(df)

      Gender  Age  Sleep Duration  Quality of Sleep  Physical Activity Level  \
0          0   41             7.0                 5                       91   
1          0   42             6.7                 7                      123   
2          1   45             8.7                 4                       49   
3          0   24             8.0                 6                        4   
4          1   18             8.8                 6                       66   
...      ...  ...             ...               ...                      ...   
1495       0   63             9.1                 7                       34   
1496       0   70             8.6                 1                       26   
1497       0   23             7.3                 5                       62   
1498       0   76             8.1                 7                       36   
1499       1   22             5.8                 7                       50   

      Stress Level  BMI Category  Heart

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
numerical_features = ['Age', 'Sleep Duration', 'Quality of Sleep',
                      'Physical Activity Level', 'Stress Level',
                      'Systolic_BP', 'Diastolic_BP']

df[numerical_features] = scaler.fit_transform(df[numerical_features])


In [ ]:
print(df.head())

   Gender       Age  Sleep Duration  Quality of Sleep  \
0       0 -0.407320       -0.834831         -0.463104   
1       0 -0.352237       -1.167994          0.659119   
2       1 -0.186988        1.053090         -1.024215   
3       0 -1.343729        0.275711          0.098007   
4       1 -1.674226        1.164144          0.098007   

   Physical Activity Level  Stress Level  BMI Category  Heart Rate  \
0                 0.831550      1.685460             1          56   
1                 1.668066     -0.427704             2          67   
2                -0.266378      0.417561             1          60   
3                -1.442730     -0.427704             1          97   
4                 0.178021     -0.850337             2          71   

   Daily Steps Sleep Disorder  ...  Occupation_Nurse  \
0         9476           None  ...              True   
1        10661           None  ...             False   
2         5033           None  ...             False   
3         16

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['Sleep Disorder'] = label_encoder.fit_transform(df['Sleep Disorder'])


In [ ]:
print(df.head())

   Gender       Age  Sleep Duration  Quality of Sleep  \
0       0 -0.407320       -0.834831         -0.463104   
1       0 -0.352237       -1.167994          0.659119   
2       1 -0.186988        1.053090         -1.024215   
3       0 -1.343729        0.275711          0.098007   
4       1 -1.674226        1.164144          0.098007   

   Physical Activity Level  Stress Level  BMI Category  Heart Rate  \
0                 0.831550      1.685460             1          56   
1                 1.668066     -0.427704             2          67   
2                -0.266378      0.417561             1          60   
3                -1.442730     -0.427704             1          97   
4                 0.178021     -0.850337             2          71   

   Daily Steps  Sleep Disorder  ...  Occupation_Nurse  \
0         9476               2  ...              True   
1        10661               2  ...             False   
2         5033               2  ...             False   
3       

In [ ]:
X = df.drop('Sleep Disorder', axis=1)
y = df['Sleep Disorder']

In [ ]:
print(X.head())

   Gender       Age  Sleep Duration  Quality of Sleep  \
0       0 -0.407320       -0.834831         -0.463104   
1       0 -0.352237       -1.167994          0.659119   
2       1 -0.186988        1.053090         -1.024215   
3       0 -1.343729        0.275711          0.098007   
4       1 -1.674226        1.164144          0.098007   

   Physical Activity Level  Stress Level  BMI Category  Heart Rate  \
0                 0.831550      1.685460             1          56   
1                 1.668066     -0.427704             2          67   
2                -0.266378      0.417561             1          60   
3                -1.442730     -0.427704             1          97   
4                 0.178021     -0.850337             2          71   

   Daily Steps  Occupation_Artist  ...  Occupation_Nurse  \
0         9476              False  ...              True   
1        10661              False  ...             False   
2         5033              False  ...             False

In [ ]:
print(y.head())

0    2
1    2
2    2
3    2
4    2
Name: Sleep Disorder, dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print(X_test)

      Gender       Age  Sleep Duration  Quality of Sleep  \
1116       1 -1.564061       -0.834831         -1.585326   
1368       0  1.245167        0.719927         -0.463104   
422        1 -0.792900       -1.056940          0.659119   
413        0  1.740913        0.608873          1.781341   
451        1  1.135001        0.275711         -0.463104   
...      ...       ...             ...               ...   
983        0  1.024836       -1.390103         -1.024215   
799        1  0.804504        0.053602         -0.463104   
1265       0  0.308758        0.942036         -0.463104   
1150       1  1.135001        0.497819          0.098007   
824        1  0.363841       -0.945886          0.098007   

      Physical Activity Level  Stress Level  BMI Category  Heart Rate  \
1116                -1.495012      1.262827             1          82   
1368                -0.998330     -0.850337             1          86   
422                  1.615784      1.685460             0   

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Create and train the Logistic Regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Step 2: Make predictions on the test set
y_pred = model.predict(X_test)

# Step 3: Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.6733333333333333

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        32
           1       0.00      0.00      0.00        20
           2       0.68      1.00      0.81       202
           3       0.00      0.00      0.00        14
           4       0.25      0.03      0.06        32

    accuracy                           0.67       300
   macro avg       0.19      0.21      0.17       300
weighted avg       0.48      0.67      0.55       300


Confusion Matrix:
 [[  0   0  31   0   1]
 [  0   0  19   0   1]
 [  0   0 201   0   1]
 [  0   0  14   0   0]
 [  0   0  31   0   1]]


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no pre

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Create and train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Step 2: Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

# Step 3: Evaluate the model
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))


Random Forest Accuracy: 0.6833333333333333

Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.03      0.06        32
           1       0.00      0.00      0.00        20
           2       0.69      1.00      0.82       202
           3       0.00      0.00      0.00        14
           4       0.50      0.09      0.16        32

    accuracy                           0.68       300
   macro avg       0.34      0.22      0.21       300
weighted avg       0.57      0.68      0.57       300


Confusion Matrix:
 [[  1   0  29   0   2]
 [  1   0  18   0   1]
 [  0   1 201   0   0]
 [  0   0  14   0   0]
 [  0   0  29   0   3]]


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create the model
dt_model = DecisionTreeClassifier(random_state=42)

# Train the model
dt_model.fit(X_train, y_train)

# Make predictions
dt_pred = dt_model.predict(X_test)

# Evaluate the model
print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))
print("\nClassification Report:\n", classification_report(y_test, dt_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, dt_pred))


Decision Tree Accuracy: 0.4866666666666667

Classification Report:
               precision    recall  f1-score   support

           0       0.17      0.22      0.19        32
           1       0.27      0.15      0.19        20
           2       0.68      0.61      0.65       202
           3       0.08      0.14      0.10        14
           4       0.24      0.31      0.27        32

    accuracy                           0.49       300
   macro avg       0.29      0.29      0.28       300
weighted avg       0.52      0.49      0.50       300


Confusion Matrix:
 [[  7   1  15   5   4]
 [  1   3  15   0   1]
 [ 28   7 124  18  25]
 [  2   0   9   2   1]
 [  3   0  19   0  10]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Step 1: Define the parameter grid
param_grid = {
    'n_estimators': [100, 150, 200],         # Number of trees
    'max_depth': [None, 10, 20],             # Depth of trees
    'min_samples_split': [2, 5],             # Minimum number of samples to split an internal node
    'min_samples_leaf': [1, 2]               # Minimum number of samples at a leaf node
}

# Step 2: Create the RandomForestClassifier model
rf = RandomForestClassifier(random_state=42)

# Step 3: Create the GridSearchCV object
grid_search = GridSearchCV(estimator=rf,
                           param_grid=param_grid,
                           cv=5,                      # 5-fold cross-validation
                           n_jobs=-1,                 # Use all CPU cores
                           verbose=2)

# Step 4: Fit the GridSearchCV to the training data
grid_search.fit(X_train, y_train)

# Step 5: Print best parameters and best score
print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)

# Step 6: Use the best estimator for predictions
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)


Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Parameters: {'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 100}
Best Accuracy: 0.63


In [ ]:
# Import necessary libraries
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

# Step 4: Create and train the SVM model
model = SVC(kernel='linear')  # You can change the kernel to 'rbf', 'poly', etc.
model.fit(X_train, y_train)

# Step 5: Make predictions on the test set
y_pred = model.predict(X_test)

# Step 6: Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{cm}')

# Classification Report
cr = classification_report(y_test, y_pred)
print(f'Classification Report:\n{cr}')


Accuracy: 67.00%
Confusion Matrix:
[[  0   0  31   0   1]
 [  0   0  19   0   1]
 [  0   1 198   0   3]
 [  0   0  14   0   0]
 [  0   0  28   1   3]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        32
           1       0.00      0.00      0.00        20
           2       0.68      0.98      0.80       202
           3       0.00      0.00      0.00        14
           4       0.38      0.09      0.15        32

    accuracy                           0.67       300
   macro avg       0.21      0.21      0.19       300
weighted avg       0.50      0.67      0.56       300



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
# Import necessary libraries
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

# Step 1: Data Preprocessing (Apply scaling if necessary)
scaler = StandardScaler()
numerical_features = ['Age', 'Sleep Duration', 'Quality of Sleep',
                      'Physical Activity Level', 'Stress Level',
                      'Systolic_BP', 'Diastolic_BP']

df[numerical_features] = scaler.fit_transform(df[numerical_features])

# Step 2: Split the data into features (X) and target (y)
X = df.drop('Sleep Disorder', axis=1)
y = df['Sleep Disorder']

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Create and train the Naive Bayes model
model = GaussianNB()
model.fit(X_train, y_train)

# Step 4: Make predictions on the test set
y_pred = model.predict(X_test)

# Step 5: Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{cm}')

# Classification Report
cr = classification_report(y_test, y_pred)
print(f'Classification Report:\n{cr}')


Accuracy: 46.67%
Confusion Matrix:
[[ 13   1   9   1   8]
 [  5   0  10   2   3]
 [ 45   1 116   6  34]
 [  1   0  10   0   3]
 [ 10   0  10   1  11]]
Classification Report:
              precision    recall  f1-score   support

           0       0.18      0.41      0.25        32
           1       0.00      0.00      0.00        20
           2       0.75      0.57      0.65       202
           3       0.00      0.00      0.00        14
           4       0.19      0.34      0.24        32

    accuracy                           0.47       300
   macro avg       0.22      0.26      0.23       300
weighted avg       0.54      0.47      0.49       300



In [ ]:
# Import necessary libraries
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

# Step 1: Data Preprocessing (Apply scaling if necessary)
scaler = StandardScaler()
numerical_features = ['Age', 'Sleep Duration', 'Quality of Sleep',
                      'Physical Activity Level', 'Stress Level',
                      'Systolic_BP', 'Diastolic_BP']

df[numerical_features] = scaler.fit_transform(df[numerical_features])

# Step 2: Split the data into features (X) and target (y)
X = df.drop('Sleep Disorder', axis=1)
y = df['Sleep Disorder']

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Create and train the KNN model
model = KNeighborsClassifier(n_neighbors=5)  # You can tune the 'n_neighbors' parameter
model.fit(X_train, y_train)

# Step 4: Make predictions on the test set
y_pred = model.predict(X_test)

# Step 5: Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{cm}')

# Classification Report
cr = classification_report(y_test, y_pred)
print(f'Classification Report:\n{cr}')


Accuracy: 56.33%
Confusion Matrix:
[[  1   0  30   1   0]
 [  3   0  16   0   1]
 [ 17   4 168   5   8]
 [  0   0  14   0   0]
 [  4   1  26   1   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.04      0.03      0.04        32
           1       0.00      0.00      0.00        20
           2       0.66      0.83      0.74       202
           3       0.00      0.00      0.00        14
           4       0.00      0.00      0.00        32

    accuracy                           0.56       300
   macro avg       0.14      0.17      0.15       300
weighted avg       0.45      0.56      0.50       300



In [ ]:
import xgboost as xgb
from sklearn.metrics import accuracy_score

# Define the XGBoost model
model = xgb.XGBClassifier(random_state=42, use_label_encoder=False)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'XGBoost Accuracy: {accuracy * 100:.2f}%')


/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:55:14] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBoost Accuracy: 66.33%


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# Define the model
model = RandomForestClassifier(random_state=42)

# Define the hyperparameters grid
param_grid = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}

# Perform GridSearchCV
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Get the best parameters
print(f"Best Parameters: {grid_search.best_params_}")

# Train the model with the best parameters
best_model = grid_search.best_estimator_

# Evaluate the model
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Improved Accuracy: {accuracy * 100:.2f}%')

# Confusion Matrix and Classification Report
cm = confusion_matrix(y_test, y_pred)
print(f'Confusion Matrix:\n{cm}')

cr = classification_report(y_test, y_pred)
print(f'Classification Report:\n{cr}')


Fitting 5 folds for each of 432 candidates, totalling 2160 fits


/usr/local/lib/python3.11/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best Parameters: {'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 50}
Improved Accuracy: 67.67%
Confusion Matrix:
[[  0   0  31   0   1]
 [  0   0  20   0   0]
 [  1   0 201   0   0]
 [  0   0  14   0   0]
 [  0   0  30   0   2]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        32
           1       0.00      0.00      0.00        20
           2       0.68      1.00      0.81       202
           3       0.00      0.00      0.00        14
           4       0.67      0.06      0.11        32

    accuracy                           0.68       300
   macro avg       0.27      0.21      0.18       300
weighted avg       0.53      0.68      0.56       300



/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
720 fits failed out of a total of 2160.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
540 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.11/dist-packages/sklearn/uti

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

NameError: name 'X_train' is not defined